version: "3.8"
services:
  ingress:
    container_name: heatpump-ingress
    image: nginx:stable-alpine
    volumes:
      - ./docker-nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - "3031:80"
  db:
    container_name: heatpump-db
    build:
      context: ./database
    environment:
      POSTGRES_USER: heatpump
      POSTGRES_DB: heatpump
      POSTGRES_PASSWORD: secret1234
    volumes:
      - ./database:/service
  backend:
    container_name: heatpump-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    command: npm run start:dev
    volumes: 
      - ./server:/service
    environment:
      PORT: 1234
      DB_USER: heatpump
      DB_DATABASE: heatpump
      DB_PASSWORD: secret1234
      DB_HOST: heatpump-db
  
  # NOTE: client doesn't work locally on m1 mac due to parcel watcher
  #client:
  #  container_name: heatpump-client
  #  build:
  #    context: ./client
  #    dockerfile: Dockerfile
  #  command: npm run start:dev
  #  volumes:
  #    - ./client:/service

volumes: 
  riffy-pg: